Uncond:
  base: ''
  path: ''
  motion_module:
  - ./models/Motion_Module/mm_sd_v15.ckpt
  seed: -1
  steps: 16
  guidance_scale: 20
  prompt:
  - The sunset is unfolding so gorgeously
  n_prompt:
  - a still image
  random_seed:
  - 594875543394099817
