Uncond:
  base: ''
  path: ''
  motion_module:
  - ./models/Motion_Module/mm_sd_v15.ckpt
  seed: -1
  steps: 16
  guidance_scale: 24
  prompt:
  - the theotokos holds a sparrow
  n_prompt:
  - confusing, ugly, flashing, cutting to different images, edits
  random_seed:
  - 15444112667572109325
