Uncond:
  base: ''
  path: ''
  motion_module:
  - ./models/Motion_Module/mm_sd_v15.ckpt
  seed: -1
  steps: 48
  guidance_scale: 8
  prompt:
  - What a gorgeous view here.
  n_prompt:
  - a still image
  random_seed:
  - 8948573927517142243
