Uncond:
  base: ''
  path: ''
  motion_module:
  - ./models/Motion_Module/mm_sd_v15.ckpt
  seed: -1
  steps: 32
  guidance_scale: 24
  prompt:
  - the theotokos holds a sparrow
  n_prompt:
  - null
  random_seed:
  - 16743055169604073395
