Uncond:
  base: ''
  path: ''
  motion_module:
  - ./models/Motion_Module/mm_sd_v15.ckpt
  seed: -1
  steps: 16
  guidance_scale: 25
  prompt:
  - the theotokos holds a sparrow
  n_prompt:
  - a still image
  random_seed:
  - 10343472829311763030
