Uncond:
  base: ''
  path: ''
  motion_module:
  - ./models/Motion_Module/mm_sd_v15.ckpt
  seed: -1
  steps: 48
  guidance_scale: 25
  prompt:
  - a psychedelic view
  n_prompt:
  - a still image
  random_seed:
  - 8229148970328452749
